---
# use \n for new line and \" for quotes inside quotes

# first stage commands
GREETINGS_TEXT: "Добрый день! Вас приветствует компания «ПроГаз»!"
OPTIONS_FIRST_TEXT: "С помощью нашего бота Вы можете посмотреть узнать о нашей компании, уровне добычи газа, а также посмотреть и редактировать информацию по Вашим заказам. Что Вы хотите узнать?"
OPTIONS_FURTHER_TEXT: "Что Вы хотите узнать?"
ABOUT_COMPANY_TEXT: "Мы — крупная газодобывающая компания. Основные направления деятельности — геологоразведка, добыча, транспортировка, хранение, переработка и реализация газа, газового конденсата, реализация газа в качестве моторного топлива, а также производство и сбыт тепло- и электроэнергии.\n «ПроГаз» видит свою миссию в надежном, эффективном и сбалансированном обеспечении потребителей природным газом."
PRODUCTION_LEVEL_TEXT: "В 2022 году «ПроГаз» добыл 412,58 млрд куб. м природного и попутного газа."

# second stage commands
ORDERS_TEXT: "Вы можете стать нашим партнером или отследить существующие договорные отношения между нами."
CHECK_CONTRACT_TEXT: "Что Вы хотите сделать с контрактом?"

# fourth stage commands
LOOK_CONTRACT_TEXT: "Введите номер контракта."
LOOK_PARTICULAR_CONTRACT_NOT_FOUND_TEXT: "К сожалению, нам не удалось найти контракт с данным номером в базе."

# other commands texts
NOT_REALIZED_YET: "Пока не реализовано. Введите \"/start\", чтобы заново вызвать окно диалога."
UNKNOWN_COMMAND: "Неизвестная команда. Введите \"/start\", чтобы вызвать окно диалога."

# database configs
DB_NAME: "database"
CONTRACT_STATUSES: [ "Active", "Finished", "Paused" ]
...